### ISSUE TITLE
Skeleton Tracking

### ISSUE THREAD

**Issue by PranshuTople** [shrirangakadam007/pykinect3.6#1]
The example code shows me live video feed from Kinect. But how to see Skeleton over the video?

**Comment by ShrirangaKadam** [comment]
Can you send me code you refered for getting skeleton data

**Comment by shrirangkadam** [comment]
The example shows that library works with python 3 by showing video stream. You need to add yours own code to get skeleton over video

**Comment by PranshuTople** [comment]
Do you have any code to retrieve the skeleton data?
